import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import random


data = pd.read_csv('Training_Essay_Data.csv')

train_data, test_data, train_labels, test_labels = train_test_split(data['text'], data['generated'], test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(stop_words='english')
train_features = vectorizer.fit_transform(train_data)

model = LogisticRegression()
model.fit(train_features, train_labels)

def guess_the_sentence():
    index = random.randint(0, len(test_data) - 1)
    sentence = test_data.iloc[index]
    true_label = test_labels.iloc[index]

    features = vectorizer.transform([sentence])
    prediction = model.predict(features)

    print(f"Sentence: {sentence}")
    guess = input("Was this sentence written by a human or generated by an AI model? (Enter 'human' or 'ai') ")

    if guess == 'human' and true_label == 0:
        print("Correct!")
    elif guess == 'ai' and true_label == 1:
        print("Correct!")
    else:
        print("Incorrect!")

guess_the_sentence()
